### ISSUE TITLE
Only Pay Later option works

### ISSUE THREAD

**Issue by syriail** [klarna/kp-android-example-app#1]
When I run the example or integrate Klarna Payments in my App using Test Credentials, the only payment method which works is Pay_Later!
I mean, performing PaymentView load returns error:
Error performing klarna.Payments.load()
How can I test other payment methods?

**Comment by mahmoudjafarinejad** [comment]
Hi syriail! Thanks for reporting this. Please check and see which payment methods are available providing your credentials, and re-open the issue if you still get the same error for the available methods.

**Comment by g-mac** [comment]
I also have this issue. With my Sandbox credentials, when I create the session I also only get "pay_later" as an option through the API response object. Thus, if I choose to change the payment method in the Android integration as suggested by the README of this repository, as such: `private val paymentCategory = KlarnaPaymentCategory.PAY_NOW` then I, too get the error
```    
{
      "action": "actionToNative",
      "sender": "KlarnaPaymentsWrapper",
      "receiver": "Native",
      "params": {
        "actionType": "errorResponse",
        "error": "ShowFormFalseError",
        "message": "Error performing Klarna.Payments.load().",
        "isPublic": "true",
        "isFatal": "true",
        "action": "Load"
      },
      "messageId": "yEDvQCXf7D"
    }", source: file:///data/user/0/com.klarna.sample.payments/files/kp_index.html?mockkp=true&storeall=true&loglevel=0 (11)
```
So.. How can I use the "payment now" option? I am quite confused to be honest.

Thanks in advance.
