### ISSUE TITLE
Initialization error callbacl no working

### ISSUE THREAD

**Issue by leon2017** [klarna/kp-android-example-app#10]
**Describe the bug**
paymentView.initialize(clientToken, returnUrl), When I made a clientToken error, no error onErrorOccurred  callback was performed

**To Reproduce**
1. Go to 'get clientToken'
2. Click on 'paymentView.initialize(clientToken, returnUrl)'
3. See error
`{
      "action": "actionToNative",
      "sender": "KlarnaPaymentsWrapper",
      "receiver": "Native",
      "params": {
        "actionType": "errorResponse",
        "error": "MissingParamError",
        "message": "Param can't be an empty or blank string for clientToken.",
        "isPublic": "false",
        "isFatal": "false"
      },
      "messageId": "cu7DPsPHF4"
    }"`

**Screenshots**
![image](https://user-images.githubusercontent.com/16276547/96666373-8c496680-1389-11eb-895d-2d76038897c5.png)

![image](https://user-images.githubusercontent.com/16276547/96665662-fe20b080-1387-11eb-90e3-02567fb43b06.png)

**Device and version:**
 - Device: SM-G935U
 - OS version: 8.0.0
 - Klarna In-App SDK version 2.0.20

**Comment by NMGuner** [comment]
Hello @leon2017, this issue has been addressed on version 2.0.22 and onward. Please try that version or above and let us know if it persists.

**Comment by leon2017** [comment]
> Hello @leon2017, this issue has been addressed on version 2.0.22 and onward. Please try that version or above and let us know if it persists.

Sorry, the version 2.0.27 reported an error
`E/chromium: [ERROR:web_contents_delegate.cc(224)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.`

![image](https://user-images.githubusercontent.com/16276547/96809182-f119c500-144c-11eb-84ca-f764d9660f4c.png)

The page is always loading

**Comment by NMGuner** [comment]
There was an issue with payments exclusively to the SDK causing infinite loading but it should be fixed now. Update to the SDK itself is not required hence would be great if you could try again with the same configuration and see that if it works for you.

**Comment by leon2017** [comment]
> There was an issue with payments exclusively to the SDK causing infinite loading but it should be fixed now. Update to the SDK itself is not required hence would be great if you could try again with the same configuration and see that if it works for you.

OK , Thx~
