### ISSUE TITLE
KlarnaPayment Check the relevant payment agreement 

### ISSUE THREAD

**Issue by leon2017** [klarna/kp-android-example-app#18]
**Describe the bug**

**To Reproduce**
1. Go to 'KlarnaPaymentCategory.SLICE_IT'
2. Click on 'more'
3. Click on 'AUTHORIZE' button

**Screenshots**

https://user-images.githubusercontent.com/16276547/105478922-cc005100-5cde-11eb-900d-a037dadd8a08.mp4

**Device and version:**

Device: SM-G935U
OS version: 8.0.0
Klarna In-App SDK version 2.0.20

**Comment by leon2017** [comment]
The project we actually worked on was the same, so I checked the official demo and it was the same

**Comment by NMGuner** [comment]
@leon2017 The issue has been solved in the Klarna Payments, hence you do not need to update the mobile SDK. Please try it again and let us know if the issue persists.

**Comment by omarbh** [comment]
we will close this issue, @leon2017 feel free to open it if you still have any question.
