### ISSUE TITLE
webview leak

### ISSUE THREAD

**Issue by billdizl** [klarna/kp-android-example-app#59]
android sdk use implementation 'com.klarna.mobile:sdk-basic:2.6.5'
<img width="504" alt="image" src="https://github.com/klarna/kp-android-example-app/assets/30317994/5347f52b-53a9-49cd-9ea9-124ef932ee57">
 @Override
    protected void onDestroy() {
        binding.paymentView.unregisterPaymentViewCallback(this);
        binding.paymentView.removeAllViews();
        super.onDestroy();
    }

what should i do solve it?

**Comment by billdizl** [comment]
> android sdk use implementation 'com.klarna.mobile:sdk-basic:2.6.5' <img alt="image" width="504" src="https://private-user-images.githubusercontent.com/30317994/289818525-5347f52b-53a9-49cd-9ea9-124ef932ee57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzU0MDQsIm5iZiI6MTcwMjM3NTEwNCwicGF0aCI6Ii8zMDMxNzk5NC8yODk4MTg1MjUtNTM0N2Y1MmItNTNhOS00OWNkLTllYTktMTI0ZWY5MzJlZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA5NTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YmE4YTJhMmE0MjVlNWNhMjAzMTRhN2MyM2QwNjZhM2YyMjVjZjdmYTJhNzE3OGYwM2VhNDg2ZTIyYzM2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DNmT2R9tZ3W1CMKOuuSTCYImfQf8IW75Xp30hhrgTSg"> @OverRide protected void onDestroy() { binding.paymentView.unregisterPaymentViewCallback(this); binding.paymentView.removeAllViews(); super.onDestroy(); }
> 
> But leak : 
![38d5b6d5382278d623344338f8c5f721](https://github.com/klarna/kp-android-example-app/assets/30317994/1cd33717-04e6-4204-a908-fea3c9c8ab61)

> what should i do solve it?

**Comment by rishiraj88** [comment]
@billdizl , in what tool or view do we see such listings about 'leaks'? These look quite nice and helpful; I want to learn them.

**Comment by billdizl** [comment]
> @billdizl , in what tool or view do we see such listings about 'leaks'? These look quite nice and helpful; I want to learn them.

@rishiraj88 https://github.com/square/leakcanary

**Comment by billdizl** [comment]
This leak need sdk to slove this leak， because sdk not expose ways to destroy payview

**Comment by NMGuner** [comment]
Thanks for reporting this with such info @billdizl, we will create a task to investigate any possible leaks. We have few internal references updated in recent releases so please consider to test this in the latest one as well.

I will close this ticket due to this being related to [the SDK](https://github.com/klarna/klarna-mobile-sdk) rather than the example app here. Feel free to open the issue there if you need to.
